# Generated by Django 3.1.7 on 2021-05-11 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo do grupo')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('limit', models.PositiveIntegerField(max_length=20, verbose_name='Limite de pessoas por grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Conteudo da mensagem')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.group', verbose_name='messages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.SmallIntegerField(choices=[(2, 'Membro'), (3, 'Apenas leitura'), (1, 'Administrador')], default=2)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.group', verbose_name='members')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='my_groups')),
            ],
        ),
    ]
