# Generated by Django 3.1.7 on 2021-05-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='limit',
            field=models.PositiveIntegerField(verbose_name='Limite de pessoas por grupo'),
        ),
        migrations.AlterField(
            model_name='groupusers',
            name='office',
            field=models.SmallIntegerField(choices=[(2, 'Membro'), (1, 'Administrador'), (3, 'Apenas leitura')], default=2),
        ),
    ]
