# Generated by Django 3.1.7 on 2021-05-11 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20210511_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.SmallIntegerField(choices=[(2, 'Membro'), (1, 'Administrador'), (3, 'Apenas leitura')], default=2)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.group', verbose_name='members')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_groups', to=settings.AUTH_USER_MODEL, verbose_name='my_groups')),
            ],
        ),
        migrations.DeleteModel(
            name='GroupUsers',
        ),
    ]
