# Generated by Django 3.1.7 on 2021-05-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210511_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_time',
            field=models.DateTimeField(auto_now=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='groupuser',
            name='office',
            field=models.SmallIntegerField(choices=[(2, 'Membro'), (3, 'Apenas leitura'), (1, 'Administrador')], default=2),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.SmallIntegerField(choices=[(2, 'Saiu do grupo'), (1, 'Entrou no grupo'), (3, 'Mensagem')], default=3),
        ),
    ]
