# Generated by Django 3.1.7 on 2021-05-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210511_0333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['date_time']},
        ),
        migrations.AlterField(
            model_name='groupuser',
            name='office',
            field=models.SmallIntegerField(choices=[(1, 'Administrador'), (3, 'Apenas leitura'), (2, 'Membro')], default=2),
        ),
    ]
