# Generated by Django 3.1.7 on 2021-05-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20210512_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupuser',
            name='office',
            field=models.SmallIntegerField(choices=[(3, 'Apenas leitura'), (1, 'Administrador'), (2, 'Membro')], default=2),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Entrou no grupo'), (3, 'Mensagem'), (2, 'Saiu do grupo')], default=3),
        ),
    ]
