# Generated by Django 3.1.7 on 2021-05-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20210512_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(default='https://static.turbosquid.com/Preview/001292/481/WV/_D.jpg', upload_to='', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='groupuser',
            name='office',
            field=models.SmallIntegerField(choices=[(1, 'Administrador'), (3, 'Apenas leitura'), (2, 'Membro')], default=2),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.SmallIntegerField(choices=[(3, 'Mensagem'), (2, 'Saiu do grupo'), (1, 'Entrou no grupo')], default=3),
        ),
    ]
