# Generated by Django 3.1.7 on 2021-05-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20210512_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.SmallIntegerField(choices=[(2, 'Saiu do grupo'), (3, 'Mensagem'), (1, 'Entrou no grupo')], default=3),
        ),
    ]
