# Generated by Django 3.1.7 on 2021-05-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20210512_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupuser',
            name='office',
            field=models.SmallIntegerField(choices=[(1, 'Administrador'), (2, 'Membro'), (3, 'Apenas leitura')], default=2),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.SmallIntegerField(choices=[(2, 'Saiu do grupo'), (3, 'Mensagem'), (1, 'Entrou no grupo')], default=3),
        ),
    ]
