# Generated by Django 3.1.7 on 2021-05-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20210512_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.SmallIntegerField(choices=[(3, 'Mensagem'), (1, 'Entrou no grupo'), (2, 'Saiu do grupo')], default=3),
        ),
    ]
